version: "3.8"

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    restart: always
    networks:
      - network
    ports:
      - 443:443

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    restart: always
    networks:
      - network
    ports:
      - 3306:3306

networks:
  network:
    driver: bridge
